# Generated by Django 5.2.8 on 2025-12-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ad",
            new_name="ads_ad_categor_6cfd35_idx",
            old_name="ads_ad_catego_07ddae_idx",
        ),
        migrations.RenameIndex(
            model_name="ad",
            new_name="ads_ad_is_urge_714661_idx",
            old_name="ads_ad_is_urge_2b89a5_idx",
        ),
        migrations.RenameIndex(
            model_name="offer",
            new_name="ads_offer_ad_id_52778a_idx",
            old_name="ads_offer_ad__3c3ef1_idx",
        ),
    ]
