# Generated by Django 5.2.8 on 2025-12-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ads",
            "0002_rename_ads_ad_catego_07ddae_idx_ads_ad_categor_6cfd35_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="budget_max",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="budget_min",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="proposed_price",
        ),
    ]
