# Generated by Django 5.2.8 on 2025-12-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_type",
        ),
    ]
