# Generated by Django 5.2.8 on 2025-12-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auditlog_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("criteria", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="completed_requests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="total_hours_helped",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="badges",
            field=models.ManyToManyField(
                blank=True, related_name="holders", to="accounts.badge"
            ),
        ),
    ]
