from django.urls import path

from .views import (
    BookingAcceptView,
    BookingCancelView,
    BookingCreateView,
    BookingDetailView,
    BookingCompleteView,
    BookingClientConfirmView,
    BookingClientDisputeView,
    BookingListView,
    BookingRescheduleDecisionView,
    BookingRescheduleView,
    BookingDeclineView,
    BookingStartView,
    BookingResolveDisputeView,
    BookingDisputeMessageView,
    DisputeListView,
    BookingAssignDisputeView,
    BookingAttachmentUploadView,
    BookingCalendarFeedView,
    BookingRepeatView,
    RecurringBookingCreateView,
    RecurringRuleListView,
    RecurringRuleCancelView,
    RecurringRuleTriggerNextView,
    RecurringRuleSkipNextView,
    ProviderDashboardView,
    ProviderActivityCSVView,
)

app_name = "bookings"

urlpatterns = [
    path("", BookingListView.as_view(), name="list"),
    path("new/", BookingCreateView.as_view(), name="create"),
    path("<int:pk>/", BookingDetailView.as_view(), name="detail"),
    path("<int:pk>/reschedule/", BookingRescheduleView.as_view(), name="reschedule"),
    path(
        "<int:pk>/reschedule/<int:request_id>/<str:decision>/",
        BookingRescheduleDecisionView.as_view(),
        name="reschedule_decision",
    ),
    path("<int:pk>/cancel/", BookingCancelView.as_view(), name="cancel"),
    path("<int:pk>/accept/", BookingAcceptView.as_view(), name="accept"),
    path("<int:pk>/decline/", BookingDeclineView.as_view(), name="decline"),
    path("<int:pk>/start/", BookingStartView.as_view(), name="start"),
    path("<int:pk>/complete/", BookingCompleteView.as_view(), name="complete"),
    path("<int:pk>/client-confirm/", BookingClientConfirmView.as_view(), name="client_confirm"),
    path("<int:pk>/client-dispute/", BookingClientDisputeView.as_view(), name="client_dispute"),
    path("<int:pk>/dispute/resolve/", BookingResolveDisputeView.as_view(), name="resolve_dispute"),
    path("<int:pk>/dispute/message/", BookingDisputeMessageView.as_view(), name="dispute_message"),
    path("<int:pk>/dispute/assign/", BookingAssignDisputeView.as_view(), name="dispute_assign"),
    path("<int:pk>/attachments/upload/", BookingAttachmentUploadView.as_view(), name="attachment_upload"),
    path("disputes/", DisputeListView.as_view(), name="disputes_list"),
    path("calendar.ics", BookingCalendarFeedView.as_view(), name="calendar_feed"),
    path("<int:pk>/repeat/", BookingRepeatView.as_view(), name="repeat"),
    path("recurring/new/", RecurringBookingCreateView.as_view(), name="recurring_create"),
    path("recurring/", RecurringRuleListView.as_view(), name="recurring_list"),
    path("recurring/<int:pk>/cancel/", RecurringRuleCancelView.as_view(), name="recurring_cancel"),
    path("recurring/<int:pk>/next/", RecurringRuleTriggerNextView.as_view(), name="recurring_next"),
    path("recurring/<int:pk>/skip/", RecurringRuleSkipNextView.as_view(), name="recurring_skip"),
    path("provider/dashboard/", ProviderDashboardView.as_view(), name="provider_dashboard"),
    path("provider/activity.csv", ProviderActivityCSVView.as_view(), name="provider_activity_csv"),
]
