# Generated by Django 5.2.8 on 2025-12-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_bidirectional"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="review",
            new_name="reviews_rev_to_user_a8fe0b_idx",
            old_name="reviews_rev_to_use_82d7f9_idx",
        ),
    ]
