# Generated by Django 5.2.8 on 2025-11-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Luni"),
                    (2, "Marti"),
                    (3, "Miercuri"),
                    (4, "Joi"),
                    (5, "Vineri"),
                    (6, "Sambata"),
                    (7, "Duminica"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Neplatit"),
                    ("authorized", "Autorizat"),
                    ("paid", "Platita"),
                    ("refunded", "Rambursat"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In asteptare"),
                    ("confirmed", "Confirmata"),
                    ("in_progress", "In curs"),
                    ("completed", "Finalizata"),
                    ("canceled", "Anulata"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
