# Generated by Django 5.2.8 on 2025-11-26 17:39

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_cancel_reason_booking_canceled_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In asteptare"),
                    ("confirmed", "Confirmata"),
                    ("in_progress", "In curs"),
                    ("completed", "Finalizata"),
                    ("canceled", "Anulata"),
                    ("declined", "Respinsa"),
                    ("reschedule_requested", "Reprogramare solicitata"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("status_changed", "Schimbare status"),
                    ("reschedule_requested", "Reprogramare propusa"),
                    ("reschedule_approved", "Reprogramare aprobata"),
                    ("reschedule_declined", "Reprogramare respinsa"),
                    ("accepted", "Acceptata"),
                    ("declined", "Respinsa"),
                    ("canceled", "Anulare"),
                    ("note", "Nota"),
                ],
                max_length=50,
            ),
        ),
    ]
