# Generated by Django 5.2.8 on 2025-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_accepted_at_booking_accepted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
