# Generated by Django 5.2.8 on 2025-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_started_at_booking_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_confirmation_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="client_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In asteptare"),
                    ("confirmed", "Confirmata"),
                    ("in_progress", "In curs"),
                    ("awaiting_client", "In asteptare confirmare client"),
                    ("completed", "Finalizata"),
                    ("canceled", "Anulata"),
                    ("declined", "Respinsa"),
                    ("reschedule_requested", "Reprogramare solicitata"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
