# Generated by Django 5.2.8 on 2025-11-26 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_client_confirmation_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In asteptare"),
                    ("confirmed", "Confirmata"),
                    ("in_progress", "In curs"),
                    ("awaiting_client", "In asteptare confirmare client"),
                    ("completed", "Finalizata"),
                    ("canceled", "Anulata"),
                    ("declined", "Respinsa"),
                    ("disputed", "In disputa"),
                    ("reschedule_requested", "Reprogramare solicitata"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("status_changed", "Schimbare status"),
                    ("reschedule_requested", "Reprogramare propusa"),
                    ("reschedule_approved", "Reprogramare aprobata"),
                    ("reschedule_declined", "Reprogramare respinsa"),
                    ("accepted", "Acceptata"),
                    ("declined", "Respinsa"),
                    ("canceled", "Anulare"),
                    ("dispute_opened", "Disputa deschisa"),
                    ("dispute_resolved", "Disputa rezolvata"),
                    ("note", "Nota"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="BookingDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Deschisa"), ("resolved", "Rezolvata")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute",
                        to="bookings.booking",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
