# Generated by Django 5.2.8 on 2025-11-26 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_booking_dispute_and_disputed_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=bookings.models.dispute_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bookings.bookingdispute",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
