# Generated by Django 5.2.8 on 2025-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_booking_confirmation_defaults"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="booking",
            new_name="bookings_bo_is_urge_e04bf7_idx",
            old_name="bookings_b_is_urge_f5ba80_idx",
        ),
        migrations.AlterField(
            model_name="reschedulerequest",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("pending", "In asteptare"),
                    ("confirmed", "Confirmata"),
                    ("in_progress", "In curs"),
                    ("awaiting_client", "In asteptare confirmare client"),
                    ("completed", "Finalizata"),
                    ("canceled", "Anulata"),
                    ("declined", "Respinsa"),
                    ("disputed", "In disputa"),
                    ("reschedule_requested", "Reprogramare solicitata"),
                ],
                max_length=20,
            ),
        ),
    ]
