# Generated by Django 5.2.8 on 2025-12-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0014_rename_bookings_b_is_urge_f5ba80_idx_bookings_bo_is_urge_e04bf7_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="extra_costs",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="price_estimated",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="price_final",
        ),
    ]
