# Generated by Django 5.2.8 on 2025-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0016_helprequest_helprequestattachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="status_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
