# Generated by Django 5.2.8 on 2025-12-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_helprequest_status_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="helprequest",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
