# Generated by Django 5.2.8 on 2025-12-29 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0019_completioncertificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="volunteerapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "accepted")),
                fields=("help_request",),
                name="unique_accepted_application_per_help_request",
            ),
        ),
    ]
