# Generated by Django 5.2.8 on 2025-12-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0020_volunteerapplication_unique_accepted_application_per_help_request",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completioncertificate",
            name="pdf_url",
        ),
        migrations.AddField(
            model_name="completioncertificate",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
